/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TestExample {
    }
}
declare global {
    interface HTMLTestExampleElement extends Components.TestExample, HTMLStencilElement {
    }
    var HTMLTestExampleElement: {
        prototype: HTMLTestExampleElement;
        new (): HTMLTestExampleElement;
    };
    interface HTMLElementTagNameMap {
        "test-example": HTMLTestExampleElement;
    }
}
declare namespace LocalJSX {
    interface TestExample {
    }
    interface IntrinsicElements {
        "test-example": TestExample;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "test-example": LocalJSX.TestExample & JSXBase.HTMLAttributes<HTMLTestExampleElement>;
        }
    }
}
