/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EloMapViewerComponent {
    }
}
declare global {
    interface HTMLEloMapViewerComponentElement extends Components.EloMapViewerComponent, HTMLStencilElement {
    }
    var HTMLEloMapViewerComponentElement: {
        prototype: HTMLEloMapViewerComponentElement;
        new (): HTMLEloMapViewerComponentElement;
    };
    interface HTMLElementTagNameMap {
        "elo-map-viewer-component": HTMLEloMapViewerComponentElement;
    }
}
declare namespace LocalJSX {
    interface EloMapViewerComponent {
    }
    interface IntrinsicElements {
        "elo-map-viewer-component": EloMapViewerComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "elo-map-viewer-component": LocalJSX.EloMapViewerComponent & JSXBase.HTMLAttributes<HTMLEloMapViewerComponentElement>;
        }
    }
}
